# -*- coding: utf-8 -*-
"""browser/views.py: documents and annexes downloaded from PloneMeeting (F8)."""
from imio.pm.wsclient.browser.views import BaseDownloadFromItemView
from imio.pm.wsclient.config import ANNEXID_MANDATORY_ERROR
from imio.pm.wsclient.config import FILENAME_MANDATORY_ERROR
from imio.pm.wsclient.config import MISSING_FILE_ERROR
from imio.pm.wsclient.config import UNABLE_TO_CONNECT_ERROR
from imio.pm.wsclient.config import UNABLE_TO_DETECT_MIMETYPE_ERROR
from imio.pm.wsclient.testing import FAKE_PM
from imio.pm.wsclient.testing import WS4PMClientTestCase


class TestBaseDownloadFromItemView(WS4PMClientTestCase):
    def test___call__(self):
        document = self.create_document()
        view = BaseDownloadFromItemView(document, self.request)
        self.assertIsNone(view())
        # PloneMeeting can not be reached
        self.settings.pm_password = u"wrongPassword"
        self.clean_memoize()
        view = BaseDownloadFromItemView(document, self.request)
        self.assertEqual(view(), document.absolute_url())
        self.assertEqual(self.messages(), [UNABLE_TO_CONNECT_ERROR])


class TestGenerateItemTemplateView(WS4PMClientTestCase):
    def test___call__(self):
        document = self.create_document()
        item = self.send_to_pm(document)
        self.messages()

        def generate(**form):
            for key, value in form.items():
                self.request.set(key, value)
            return document.restrictedTraverse(
                "@@generate_document_from_plonemeeting"
            )()

        # nothing is generated, the user is redirected to the element with a message
        self.assertEqual(generate(), document.absolute_url())
        self.assertEqual(self.messages(), [UNABLE_TO_DETECT_MIMETYPE_ERROR])
        self.assertEqual(generate(templateFormat="odt"), document.absolute_url())
        self.assertEqual(self.messages(), [FILENAME_MANDATORY_ERROR])
        self.assertEqual(generate(templateFilename="filename"), document.absolute_url())
        self.assertEqual(
            self.messages(),
            [
                u"An error occured while generating the document in PloneMeeting! "
                u"The error message was : Server raised fault: "
                u"'You can not access this item!'"
            ],
        )
        self.assertEqual(generate(itemUID=item["UID"]), document.absolute_url())
        self.assertEqual(
            self.messages(),
            [
                u"An error occured while generating the document in PloneMeeting! "
                u"The error message was : Server raised fault: "
                u"'You can not access this template!'"
            ],
        )
        # the document generated by PloneMeeting
        self.assertEqual(
            generate(templateId="itemTemplate__format__odt"), b"Meeting item (odt)"
        )
        self.assertEqual(
            self.request.response.getHeader("content-type"),
            "application/vnd.oasis.opendocument.text",
        )
        self.assertEqual(
            self.request.response.getHeader("content-disposition"),
            'inline;filename="filename.odt"',
        )


class TestDownloadAnnexFromItemView(WS4PMClientTestCase):
    def test___call__(self):
        document = self.create_document()

        def download(**form):
            for key, value in form.items():
                self.request.set(key, value)
            return document.restrictedTraverse("@@download_annex_from_plonemeeting")()

        self.assertEqual(download(), document.absolute_url())
        self.assertEqual(self.messages(), [ANNEXID_MANDATORY_ERROR])
        # no item
        self.assertEqual(
            download(annex_id="annexe.txt", itemUID="unknown"), document.absolute_url()
        )
        self.assertEqual(self.messages(), [MISSING_FILE_ERROR])
        # the annex of the item
        item = FAKE_PM.add_item(
            u"plonemeeting-assembly",
            u"developers",
            u"pmCreator1",
            title=u"Item",
            annexes=[
                {
                    "@type": "annex",
                    "title": u"Annexe",
                    "file": {"filename": u"annexe.txt", "data": u"SGVsbG8h"},
                }
            ],
        )
        self.assertEqual(download(itemUID=item["UID"]), b"Hello!")
        self.assertEqual(self.request.response.getHeader("content-type"), "text/plain")
        self.assertEqual(
            self.request.response.getHeader("content-disposition"),
            'inline;filename="annexe.txt"',
        )
        # another annex id
        self.assertIsNone(download(annex_id="other.txt"))
