name: Tests

on:
  push:
    branches:
      - gha
  workflow_dispatch:

jobs:
  tests:
    runs-on: gha-runners-delib-py2
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: "2.7.18"
            plone-version: "4.3"
    services:
      libreoffice:
        image: imiobe/libreoffice:7.3
        ports:
          - 2002:2002
        volumes:
          - /tmp:/tmp
          - /var/tmp:/var/tmp
    steps:
      - name: Needed for local development
        if: ${{ env.ACT }}
        run: echo /home/runner/externals/node20/bin >> $GITHUB_PATH
        shell: bash
      - name: Launch soffice
        run: soffice '--accept=socket,host=0.0.0.0,port=2002;urp;StarOffice.ServiceManager' --nologo --headless --nofirststartwizard --norestore &
        shell: bash
      - name: Run tests
        uses: IMIO/gha/plone-package-test-notify@main
        env:
          cache-name: cache-eggs
        with:
          CACHE_KEY: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.python-version }}
          TEST_COMMAND: OO_SERVER=localhost OO_PORT=2002 bin/test -t \!robot
          INSTALL_DEPENDENCIES_COMMANDS: |
            sudo pip install -r requirements-${{ matrix.plone-version }}.txt
          MATTERMOST_WEBHOOK_URL: ${{ secrets.DELIB_MATTERMOST_WEBHOOK_URL }}